### ISSUE TITLE
Widget servicegroup a des duplications de services

### ISSUE THREAD

**Issue by centreon** [Centreon-Widgets/centreon-widget-servicegroup-monitoring#4]
---

Author Name: **m m** (m m)
Original Redmine Issue: 4884, https://forge.centreon.com/issues/4884
Original Date: 2013-09-16

---

Le widget de servicegroup version: 1.1.0 a des duplications quant il se base sur ma base NDO.

**Comment by leoncx** [comment]
Duplicate #2
